# Generated by Django 2.0 on 2018-09-07 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.BlogType'),
        ),
    ]
